name: Run Spider Script

on:
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 检查并安装依赖
      - name: Check and install dependencies
        run: |
          if test -f "requirements.txt"; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found, skipping dependency installation."
          fi

      - name: Run spider.py
        run: |
          python spider.py

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move Excel file to dist
        run: mv *.xlsx dist/

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/
