name: Run Spider Script

on:
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装 Firefox 和 GeckoDriver（使用非 Snap 版本）
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo snap remove firefox || true
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin-Priority: 1001' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          sudo apt-get update

          # 禁用 needrestart 的重启检查
          echo "\$nrconf{restart} = 'a';" | sudo tee /etc/needrestart/needrestart.conf

          # 确保所有 Firefox 实例都已终止
          pkill -f firefox || true

          # 检查并安装 Firefox，如果未安装则进行安装
          if ! command -v firefox &> /dev/null; then
            sudo apt-get install -y firefox
          fi

          # 下载并安装 GeckoDriver
          wget -q https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-v0.33.0-linux64.tar.gz

          # 安装完毕后立即删除 needrestart，防止后续重启检查
          sudo apt-get remove -y needrestart || true

      # 安装 Python 依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl requests

      # 运行 spider.py 文件
      - name: Run spider.py
        run: |
          python spider.py

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move Excel file to dist
        run: mv *.xlsx dist/

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/
