name: Run Spider Script

on:
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl requests

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          # Remove snap version of Firefox if it exists
          sudo snap remove firefox || true
          # Add Mozilla's PPA to get the latest Firefox
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt-get update
          # Install Firefox
          sudo apt-get install -y firefox || exit 1
          # Download and set up GeckoDriver
          wget -q https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver
          rm geckodriver-v0.33.0-linux64.tar.gz

      - name: Kill any existing Firefox processes
        run: pkill -f firefox

      - name: Run spider.py
        run: |
          python spider.py

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move Excel file to dist
        run: mv *.xlsx dist/

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/
