name: Run Spider Script

on:
  workflow_dispatch:  # 允许手工触发

jobs:
  run-spider:
    runs-on: ubuntu-latest  # 运行在最新的 Ubuntu 环境中

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # 检出代码仓库

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager beautifulsoup4 pandas openpyxl requests  # 安装依赖

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo snap remove firefox || true
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          echo 'Pin-Priority: 1001' | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
          sudo apt-get update
          sudo apt-get install -y firefox || exit 1
          wget -q https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          rm geckodriver-v0.33.0-linux64.tar.gz

      - name: Run spider.py
        run: |
          python spider.py

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move Excel file to dist
        run: mv *.xlsx dist/

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/
